server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_film?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #显示true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0

imageFilePath: D://WorkPlace/ideaProjects/film/src/main/webapp/static/fileImages/
